---
title: Matching pigeons
output:
  md_document:
    variant: markdown_github
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "./output"
    )
  })
---

```{r}
rm(list=ls())
library('R2jags')

source("src/pigeon_helpers.R")

data <- pigeons_to_jags()
```

```{r}
options(repr.plot.width  = 15,
        repr.plot.height = 10)

layout(matrix(1:6, nrow=2))

for(bb in unique(data$pigeons$bird)){
    brd_data <- subset(data$pigeons, bird==bb)
    plot(NULL, xlim=c(-5,5), ylim=c(-5,5))
    abline(0, 1, lty='dashed')
    points(log(brd_data$n_reinf_right/brd_data$n_reinf_left),
           log(brd_data$n_resp_right/brd_data$n_resp_left))
}
```

```{r}
priors <- list(mean_alpha = 0.0,
               sd_alpha   = 1/sqrt(.1),
               mean_beta  = 0.0,
               sd_beta    = 1/sqrt(.1),
               shape_tau  = 2.0,
               rate_tau   = 0.5)

observed <- list(
    Br               = data$pigeons$n_resp_right,
    Bl               = data$pigeons$n_resp_left,
    Wr               = data$pigeons$n_reinf_right,
    Wl               = data$pigeons$n_reinf_left,
    birds            = data$birds,
    mean_alpha_prior = priors$mean_alpha,
    sd_alpha_prior   = priors$sd_alpha,
    mean_beta_prior  = priors$mean_beta,
    sd_beta_prior    = priors$sd_beta,
    shape_tau_prior  = priors$shape_tau,
    rate_tau_prior   = priors$rate_tau,
    n_obs            = length(data$sessions),
    n_birds          = length(unique(data$birds))
)

unobserved <- c('alpha', 'beta', 'tau', 'lambda_Br', 'lambda_Bl', 'Br_post', 'Bl_post')

model.file.name = 'generative_matching_individual.bug'

write(
    'model{

        for(b in 1:n_birds) {
            alpha[b] ~ dnorm(mean_alpha_prior, pow(sd_alpha_prior, -2))T(-2,2)
            beta[b]  ~ dnorm(mean_beta_prior , pow(sd_beta_prior , -2))T(-2,2)
            tau[b]   ~ dgamma(shape_tau_prior, rate_tau_prior)T(0.01,)
        }
    
        for(i in 1:n_obs) {
            lambda_Br[i] ~ dlnorm( alpha[birds[i]]/2 + beta[birds[i]] * log(Wr[i])/2, tau[birds[i]])
            lambda_Bl[i] ~ dlnorm(-alpha[birds[i]]/2 - beta[birds[i]] * log(Wl[i])/2, tau[birds[i]])
            Br[i] ~ dpois(lambda_Br[i])
            Bl[i] ~ dpois(lambda_Bl[i])
            Br_post[i] ~ dpois(lambda_Br[i])
            Bl_post[i] ~ dpois(lambda_Bl[i])
        }

    }',
    model.file.name
)

bayes <- jags(
    data = observed,
    parameters.to.save = unobserved,
    model.file = model.file.name, n.iter = 20000, n.chains = 4, n.burnin = 100
)
  
```

```{r}
summary(bayes$BUGSoutput$summary[,c('Rhat','n.eff')])
```

```{r}
nds <- bayes$BUGSoutput$sims.list
summary(nds$alpha)
summary(nds$beta)
```

```{r}

layout(matrix(1:2,nrow=1))

plot_marginal('alpha', nds)
plot_marginal('beta', nds)
```

```{r}
layout(matrix(1:2,nrow=1))

plot_marginal <- function(){
  par(cex.axis=1.5)
  layout(matrix(1:6,ncol=3))
  for(brd in 1:6){
    plot(nds$alpha[,brd],nds$beta[,brd],col=bird_colors[brd])
    axis(1)
  }
}
plot_marginal()
```

