#!/bin/bash

DEBIAN_FRONTEND=interactive

sudo apt install git=1:2.25.1-1ubuntu3.8 &> /dev/null

cp /vagrant/vm/.secrets/.ssh/id_rsa_vm /home/vagrant/.ssh/id_rsa
cp /vagrant/vm/.secrets/.ssh/config    /home/vagrant/.ssh/

chmod 600 /home/vagrant/.ssh/id_rsa

ssh-keyscan github.com >> .ssh/known_hosts


